---
sudo: false
dist: bionic
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - {python: '3.6'}
    - {python: '3.7'}
    - {python: '3.8'}
    - {python: 'nightly'}

    - {python: '3.7', env: TOXENV=docs}
    - {python: '3.7', env: TOXENV=quality}

  allow_failures:
    - python: 'nightly'

install:
  - travis_retry pip install tox tox-travis

script:
  - tox
